name: Build APK Otomatis

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Fix Struktur Cordova (Paksa Inisialisasi)
      run: |
        npm install -g cordova
        echo '{"name": "com.appbuilder.cid.sann", "displayName": "AppBuilder"}' > package.json

    - name: Proses Build APK
      run: |
        cordova platform add android@12.0.0 --no-telemetry
        cordova build android --debug --no-telemetry

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Build-APK
        path: |
          platforms/android/app/build/outputs/apk/debug/*.apk
